### ISSUE TITLE
Dry Run Writes Updated package.json Version to Disk

### ISSUE THREAD

**Issue by mjhasbach** [AlexKVal/release-script#25]
Dry running writes the updated package.json version to disk, necessitating a Git revert before the actual run. I was wondering if that was intentional, and if so, why, because the console also displays the updated version?

**Comment by AlexKVal** [comment]
Intentional.
And temporary folders with their respective content are not being deleted by script too.
That's for checking of all with dry run  for complex project as `React-Bootstrap`.

E.g. in `R-B` documents site pages are being generated and via dry-run we are able to check
that all is OK before releasing `npm`, `bower` libs and publishing docs site.

We are reverting changes after dry-run back by simple command:
`git checkout reset --hard`

## 

console could display the change, but an actual change could not be applied in reality (because of some subtle bug for example).

**Comment by mjhasbach** [comment]
Cool, thanks

**Comment by AlexKVal** [comment]
You are welcome :cherries:
