### ISSUE TITLE
getOwnerAndRepo: Support package.json String repository Property

### ISSUE THREAD

**Issue by mjhasbach** [AlexKVal/release-script#5]
`getOwnerAndRepo` only works if the `repository` property is an object containing a string `url` property. The `repository` property may also be a string (see [the repository property documentation](https://docs.npmjs.com/files/package.json#repository)).

Example:

```
{
...
  "repository": "AlexKVal/release-script"
...
}
```

**Comment by AlexKVal** [comment]
This line https://github.com/AlexKVal/release-script/blob/master/src/release.js#L129 was made exactly to address that case, but I had screwed it here [src#L223](https://github.com/AlexKVal/release-script/commit/9071d8dea62c458db63eda630c0a629c755c71bd#diff-a1ca48439c82c10c6224f7c126531cf8L223) :smile: 

## 

Fixed by https://github.com/AlexKVal/release-script/commit/9071d8dea62c458db63eda630c0a629c755c71bd
@mjhasbach  Thank you :cherries:

**Comment by mjhasbach** [comment]
Awesome! I'll test after the next version is released.

**Comment by AlexKVal** [comment]
Done :smile: 
https://github.com/AlexKVal/release-script/releases/tag/v0.2.5
https://www.npmjs.com/package/release-script v0.2.5

**Comment by mjhasbach** [comment]
Works great, thanks!

**Comment by AlexKVal** [comment]
:blush:
